
sources = files(
      'Spoon.cpp'
    , 'MapProjection.cpp'
    , 'GeoJsonSimplifyHandler.cpp'
    , 'GeoJson.cpp'
    , 'BoundsDisplay.cpp'
    , 'WeatherConfigGrid.cpp'
    , 'WeatherConfig.cpp'
    , 'WeatherDialog.cpp'
)
weather_sources = files(
    'Weather.cpp'
    , 'RealEarth.cpp'
    , 'WebMapService.cpp'
    , 'GeoCoordinate.cpp'
)
sources += weather_sources
flight_sources = files(
    'Flight.cpp'
    , 'Flights.cpp'
    , 'OpenskyFlights.cpp'
)
sources += flight_sources


